# 赞助页面与收款码
custom:
  - "https://github.com/GOLDhjy/GCompare/blob/main/docs/SPONSORSHIP.md"
  - "https://paypal.me/GoldHjy"
  - "https://raw.githubusercontent.com/GOLDhjy/GCompare/main/public/Images/%E5%BE%AE%E4%BF%A1.jpg"
  - "https://raw.githubusercontent.com/GOLDhjy/GCompare/main/public/Images/%E6%94%AF%E4%BB%98%E5%AE%9D.jpg"
